# Generated by Django 5.2 on 2026-07-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название книги"),
                ),
                (
                    "isbn",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        verbose_name="Международный стандартный книжный номер",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("NON_FICTION", "Non-Fiction"),
                            ("SCIENCE", "Science"),
                            ("FANTASY", "Fantasy"),
                            ("MYSTERY", "Mystery"),
                            ("ROMANCE", "Romance"),
                            ("HISTORY", "History"),
                            ("BIOGRAPHY", "Biography"),
                            ("POETRY", "Poetry"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Жанр книги",
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(verbose_name="Год публикации"),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Публикатор"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Примечание"),
                ),
                (
                    "total_copies",
                    models.IntegerField(default=1, verbose_name="Количество копий"),
                ),
                (
                    "available_copies",
                    models.IntegerField(default=1, verbose_name="Доступные копии"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="authors.author",
                        verbose_name="Автор книги",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
