# Generated by Django 5.2 on 2026-07-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("NON_FICTION", "Non-Fiction"),
                            ("SCIENCE", "Science"),
                            ("FANTASY", "Fantasy"),
                            ("MYSTERY", "Mystery"),
                            ("ROMANCE", "Romance"),
                            ("HISTORY", "History"),
                            ("BIOGRAPHY", "Biography"),
                            ("POETRY", "Poetry"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("publication_year", models.IntegerField()),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("total_copies", models.IntegerField(default=1)),
                ("available_copies", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="authors.author",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
